#!/usr/bin/env/python
""" Offers a service to add two numbers

    SERVICES:
      add_them (me495_practice/fake_service) - adds two numbers
"""

import rospy
import me495_practice.hardmath as hardmath
from me495_practice.srv import fake_srv, fake_srvResponse

def handle(a, b):
    """ Handle the add_two request 
    ARGS:
     a - one number to add
     b - another number to add
    RETURNS:
     a fake_srvResponse that is the sum of a and b
"""
    return fake_srvResponse(hardmath.add_two(a, b))

if __name__ == "__main__":
    rospy.init_node('add_me')
    srv = rospy.Service("add_two", fake_srv, handle)
