#!/usr/bin/env python
""" Offers a service to add two numbers

    SERVICES:
      add_them (me495_practice/fake_service) - adds two numbers
"""

import rospy
import me495_practices.hardmath as hardmath
from me495_practices.srv import TwoResult, TwoResultResponse

def handle(req):
    """ Handle the add_two request 
    ARGS:
      req - the service request
    RETURNS:
     a fake_srvResponse that is the sum of a and b
"""
    return TwoResultResponse(hardmath.add_two(req.input1, req.input2))

if __name__ == "__main__":
    rospy.init_node('add_me')
    srv = rospy.Service("add_two", TwoResult, handle)
    rospy.spin()
